name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: echo "🖥️ The workflow is now ready to update the documentation."
      - name: Run build
        run: |
          bash ${{ github.workspace }}/buildfiles/build.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update documentation